name: build

on:
  repository_dispatch:
    types: [build2]

jobs:
  base-build2:
    runs-on: ubuntu-24.04
    name: workshop-build
    steps:

      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ghcr.io/${{ github.repository }}-part2
          tags: |
            dev
          labels: |
            annotation-index.org.opencontainers.image.source=https://github.com/${{ github.repository }}
            annotation-index.org.opencontainers.image.licenses=MIT
            annotation-index.org.opencontainers.image.description=A repository containing the build steps for the ccpbiosim workshop introducing enhanced sampling.
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Authenticate with GHCR
        id: ghcr-auth
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.BUILD_TOKEN}}

      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v6.18.0
        with:
          file: Dockerfile2
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}

      - name: Dispatch Tests
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.BUILD_TOKEN }}
          repository: ${{ github.repository }}
          event-type: test2
          client-payload: '{"tag": "${{ github.event.client_payload.tag }}"}'
