name: build

on:
  repository_dispatch:
    types: [build]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Base container version tag'
        required: true
        default: 'null'

jobs:
  base-build1:
    runs-on: ubuntu-24.04
    name: workshop-build
    steps:
      - name: tag
        id: version-tag
        run: |
          if [ ${{ github.event.inputs.tag }} != 'null' ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.event.client_payload.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Dispatch Contianer 1 Tests
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.BUILD_TOKEN }}
          repository: ${{ github.repository }}
          event-type: build1
          client-payload: '{"tag": "${{ github.event.client_payload.tag }}"}'

      - name: Dispatch Contianer 2 Tests
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.BUILD_TOKEN }}
          repository: ${{ github.repository }}
          event-type: build2
          client-payload: '{"tag": "${{ steps.version-tag.outputs.tag }}"}'
